- src/app/components/elements/modals/RequiredAccountInformationModal.tsx
- src/app/components/elements/panels/UserPassword.tsx
- src/app/components/pages/LogIn.tsx
- src/app/components/pages/MyAccount.tsx
- src/app/components/pages/Registration.tsx
- src/app/services/validation.ts
- src/app/state/actions/index.tsx
- src/mocks/handlers.ts
- src/scss/common/registration.scss
- src/test/pages/MyAccount.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/55
> [55]: changed error messages on Login page, My Account, Registration & added tests for My Account page

- src/app/components/elements/inputs/DateInput.tsx
- src/app/components/elements/inputs/EmailInput.tsx
- src/app/components/elements/inputs/GenderInput.tsx
- src/app/components/elements/inputs/PasswordInput.tsx
- src/app/components/elements/inputs/RegistrationContext.tsx
- src/app/components/elements/inputs/RegistrationDobInput.tsx
- src/app/components/elements/inputs/RegistrationEmailPreference.tsx
- src/app/components/elements/inputs/RegistrationNameInput.tsx
- src/app/components/elements/inputs/SchoolInput.tsx
- src/app/components/elements/inputs/TrueFalseRadioInput.tsx
- src/app/components/elements/modals/RequiredAccountInformationModal.tsx
- src/app/components/elements/panels/UserDetails.tsx
- src/app/components/elements/panels/UserEmailPreferences.tsx
- src/app/components/elements/panels/UserPassword.tsx
- src/app/components/handlers/LogOutHandler.tsx
- src/app/components/navigation/IsaacApp.tsx
- src/app/components/pages/LogIn.tsx
- src/app/components/pages/MyAccount.tsx
- src/app/components/pages/Registration.tsx
- src/app/components/pages/StudentRegistration.tsx
- src/app/components/pages/TeacherRegistration.tsx
- src/app/services/constants.ts
- src/app/state/actions/index.tsx
- src/mocks/data.ts
- src/scss/common/forms.scss
- src/scss/common/registration.scss
- src/test/pages/MyAccount.test.tsx
- src/test/pages/Registration.test.tsx
- src/test/pages/StudentRegistration.test.tsx
New student registration feature https://github.com/isaaccomputerscience/isaac-cs-issues/issues/48
Teacher page is there as placeholder but not yet worked on
> Added new landing page, student registration page and tests

- src/app/components/elements/Dashboard.tsx
- src/app/components/elements/inputs/RegistrationEmailPreference.tsx
- src/app/components/elements/panels/UserEmailPreferences.tsx
- src/app/components/pages/Events.tsx
- src/app/components/pages/TeacherFeatures.tsx
- src/app/components/site/Homepage.tsx
- src/app/components/site/NavigationBar.tsx
- src/app/services/constants.ts
- src/test/pages/IsaacApp.test.tsx
- changed event filter to check for booster and discovery
> removed Teacher CPD, Masterclass and Livestream events 

- src/app/components/elements/PromoContent.tsx
- src/app/components/site/Homepage.tsx
- src/mocks/data.ts
- src/test/pages/IsaacApp.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/108
> different promo item for logged in vs teachers

- src/app/components/elements/inputs/RegistrationDobInput.tsx
- src/mocks/data.ts
- src/test/components/elements/Dashboard.test.tsx
- src/test/components/elements/inputs/RegistrationDobInput.test.tsx
- src/test/components/elements/inputs/RegistrationEmailPreference.test.tsx
- src/test/components/elements/inputs/RegistrationNameInput.test.tsx
- src/test/components/elements/inputs/RegistrationSubmit.test.tsx
- src/test/pages/IsaacApp.test.tsx
- src/test/utils.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/107
> additional unit tests for Registration components

- src/app/components/elements/panels/EventOverviews.tsx
- src/app/components/pages/EventManager.tsx
- src/mocks/data.ts
- src/scss/common/events.scss
- src/test/components/elements/panels/EventOverviews.test.tsx
- src/test/components/panels/EventOverviews.test.tsx
- src/test/services/eventAttendancePercentage.test.tsx
now also showing absence and attendance %
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/161
> changes to table layout of Event booking admin

- config/jest/jest.config.common.js
Tests running a bit slow in pipeline so increased timeout
> Test timeouts

- src/app/components/navigation/IsaacApp.tsx
- src/app/components/site/Routes.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/160
> Content behind login

- src/app/components/elements/EventBookingForm.tsx
- src/test/components/elements/EventBookingForm.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/199
refactored EventBookingForm, added PII message, added tests
> PII message to EventBookingForm

- src/app/components/elements/list-groups/ListGroupFooter.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/201
This one will also require a content deployment for the text change inside the safeguarding page.
> added safeguarding link to footer

- src/app/components/elements/EventBookingForm.tsx
- src/app/components/pages/EventDetails.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/200
Hiding button to book a place if deadline has passed, as that is no longer possible with API change.
Also fixed rendering problem with some inputs on the event booking form
> deadline now applies to events waitlist

- src/app/components/elements/panels/EventOverviews.tsx
- src/app/components/pages/EventManager.tsx
- src/app/components/site/Routes.tsx
- src/test/pages/EventManager.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/202
> added event toolkit buttons + tests

- src/app/components/pages/Registration.tsx
- src/app/components/pages/TeacherRegistration.tsx
- src/test/pages/Registration.test.tsx
- src/test/pages/StudentRegistration.test.tsx
- src/test/pages/TeacherRegistration.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/222
> Teacher registration warning

- src/app/components/elements/modals/RequiredAccountInformationModal.tsx
- src/app/components/elements/panels/UserDetails.tsx
- src/app/components/pages/TeacherRegistration.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/221
> teacher conditions wording change

- src/app/components/elements/panels/Banner.tsx
- src/app/components/pages/Events.tsx
- src/scss/common/elements.scss
- src/scss/common/events.scss
- src/test/components/elements/panels/Banner.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/223
Adding alternative banner colours
> Banner colour change

- src/app/components/elements/cards/QuestionCard.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/281
> added GA tracking for Next and Go to buttons on question finder

- public/assets/twitter_icon.svg
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/257
> updated twitter/ X logo

- src/app/components/pages/Events.tsx
Changed NCCE banner on Events page to only appear for users logged in as teachers or above
> NCCE Banner only for teacher+ users

- config/webpack.config.common.js
- package.json
- public/index.html
- src/app/components/elements/views/ActivityGraph.tsx
- src/app/components/elements/views/QuestionProgressCharts.tsx
- src/app/components/pages/MyProgress.tsx
- src/scss/common/my-progress.scss
- yarn.lock
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/116
> billboardjs upgrade

- src/IsaacAppTypes.tsx
- src/app/components/elements/EventBookingForm.tsx
- src/app/components/elements/panels/EventAttendance.tsx
- src/app/components/elements/panels/ManageExistingBookings.tsx
- src/test/components/elements/EventBookingForm.test.tsx
- src/test/components/elements/panels/ManageExistingBookings.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/315
> renamed medical to dietary requirements

- src/app/components/elements/inputs/SchoolInput.tsx
- src/app/components/pages/AdminUserManager.tsx
- src/app/services/user.ts
- src/test/pages/AdminUserManager.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/256
> admin user search by school

- src/app/components/site/NavigationBar.tsx
- src/test/pages/IsaacApp.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/358
> removed workbooks from student Learn nav menu

- src/IsaacAppTypes.tsx
- src/app/components/elements/EventBookingForm.tsx
- src/mocks/data.ts
- src/test/components/elements/EventBookingForm.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/373
> removed level of teaching experience

- src/app/components/elements/inputs/RegistrationNameInput.tsx
- src/app/components/elements/modals/RequiredAccountInformationModal.tsx
- src/app/services/validation.ts
- src/test/pages/RequiredInformationModal.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/381
> added givenName and familyName to RequiredAccountInformationModal

- src/app/components/elements/modals/ActiveModal.tsx
- src/app/components/elements/modals/ActiveModals.tsx
- src/app/components/elements/modals/NotificationModal.tsx
- src/test/components/elements/modals/NotificationModal.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/389
> annual survey popup

- src/app/components/elements/PageTitle.tsx
- src/app/components/elements/inputs/EditablePageTitle.tsx
- src/app/components/pages/Gameboard.tsx
- src/scss/common/header.scss
- src/test/components/elements/PageTitle.test.tsx
- src/test/components/elements/inputs/EditablePageTitle.test.tsx
- src/test/pages/Gameboard.test.tsx
- src/test/setupTests.ts
- src/test/utils.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/374
> editable gameboard title

- src/app/components/elements/CareersBanner.tsx
- src/test/components/elements/CareersBanner.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/399
> added 'more careers videos' button + tests

- src/app/components/site/Routes.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/409
> removed login requirement for /topics/gcse and /topics/a_level

- src/scss/common/headings.scss
- src/scss/common/typography.scss
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/52
> Minor UI change to the HR elements #52

- src/app/assets/career_videos.json
- src/app/components/pages/Careers.tsx
- src/test/pages/Careers.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/406
> added links to content for Career Videos

- src/test/pages/AdminUserManager.test.tsx
- src/test/pages/Groups.test.tsx
- src/test/pages/TeacherRequest.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/383
> intermittent test failures

- src/app/components/elements/panels/EventOverviews.tsx
- src/app/services/api.ts
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/426
> Event admin pagination improvements

- src/IsaacApiTypesAutoGenerated.tsx
Relation to this ticket: https://github.com/isaaccomputerscience/isaac-cs-issues/issues/416
> updating DTO auto generated file

- src/app/components/elements/cards/EventCard.tsx
- src/test/components/elements/cards/EventCard.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/419
> Join Event button added to EventCard

- config/webpack.config.common.js
- package.json
- src/app/state/middleware/userConsistencyChecker.tsx
- src/index-renderer.tsx
- src/index.tsx
- src/test/setupTests.ts
- yarn.lock
Ticket: https://github.com/isaaccomputerscience/isaac-cs-issues/issues/44
> Webpack Config changes (#44)

- .github/dependabot.yml
[Ticket](https://github.com/isaaccomputerscience/isaac-cs-issues/issues/245)
Fix formatting issue and ecosystem name
> [245]: FE Dependabot configuration pt2

- config/webpack.config.common.js
- package.json
- public/mockServiceWorker.js
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/437
> removed terser-webpack-plugin

- src/app/components/elements/CareersBanner.tsx
- src/app/components/elements/PromoContent.tsx
- src/scss/common/careers.scss
- src/test/components/elements/CareersBanner.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/411
> Heading on Homepage

- src/app/components/elements/panels/AddUsersToBooking.tsx
- src/app/components/elements/panels/EventAttendance.tsx
- src/app/components/elements/panels/ManageExistingBookings.tsx
- src/app/services/api.ts
- src/app/state/actions/index.tsx
- src/test/components/elements/panels/EventAttendance.test.tsx
- src/test/pages/EventManager.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/417
> Event Admin bulk attendance marking

- src/app/services/highlightJs.ts
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/45
> added java and vba supports to highlightjs

- src/app/components/elements/panels/EventAttendance.tsx
- src/app/components/elements/panels/ManageExistingBookings.tsx
- src/test/components/elements/panels/EventAttendance.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/452
> attendance remaining button for mass attendance marking

- src/app/components/pages/EventDetails.tsx
- src/app/services/events.tsx
- src/test/pages/EventDetails.test.tsx
& now for all logged in users 
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/459
> add to calendar button changed to generate .ics file

- src/app/components/elements/panels/EventAttendance.tsx
- src/test/components/elements/panels/EventAttendance.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/461
> filtering attendance panel to only show confirmed/attended/absent bookings

- src/app/services/validation.ts
- src/test/components/elements/inputs/RegistrationNameInput.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/450
>  Limit length and content of account details

- src/IsaacApiTypesAutoGenerated.tsx
Ticket in relation - https://github.com/isaaccomputerscience/isaac-cs-issues/issues/469
> updated DTO types in React for eventSurvey field

- src/IsaacApiTypesAutoGenerated.tsx
Related to this ticket: https://github.com/isaaccomputerscience/isaac-cs-issues/issues/469
> update DTO types in eventSurvey to String

- src/app/components/site/NavigationBar.tsx
- src/app/components/site/Routes.tsx
- src/test/pages/IsaacApp.test.tsx
https://github.com/isaaccomputerscience/isaac-cs-issues/issues/481
> Added new route and link for gcse teaching order

- src/app/components/navigation/IsaacApp.tsx
Added user agent to concepts tracked route for google bot to pass through to concepts
> User agent to concepts

- src/app/components/pages/Events.tsx
ticket link: https://github.com/orgs/isaaccomputerscience/projects/3/views/75?pane=issue&itemId=97252071&issue=isaaccomputerscience%7Cisaac-cs-issues%7C589
Before fix:
After fix:
> Add logic to sort the events in newest first order

- src/app/components/elements/EventBookingForm.tsx
Ticket: https://github.com/isaaccomputerscience/isaac-cs-issues/issues/664
This pull request updates the EventBookingForm and related components to add the required attribute to various input fields. Specifically, it:
- Updates SchoolYearGroup, AccessibilityAndDietaryRequirements, and InputWithLabel components to accept a required prop.
- Passes the required prop to the relevant input elements, enforcing form validation for required fields.
- Updates the EventBookingForm to use the new required prop in all appropriate places.
> Updated form components with required validation
